In [ ]:
import pandas as pd
import numpy as np

path ='/content/drive/MyDrive/Colab Notebooks/breast_cancer.csv'

#datefream으로 읽기
df = pd.read_csv(path)

df

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [ ]:
df2=df.drop('label',axis=1)
df.head()

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
y=df2['worst compactness']
y.value_counts()
y

0      0.66560
1      0.18660
2      0.42450
3      0.86630
4      0.20500
        ...
564    0.21130
565    0.19220
566    0.30940
567    0.86810
568    0.06444
Name: worst compactness, Length: 569, dtype: float64

In [ ]:
X=df2.drop('worst compactness',axis=1)
X.head()

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.2416,0.1860,0.2750,0.08902
2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4504,0.2430,0.3613,0.08758
3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,0.009208,14.91,26.50,98.87,567.7,0.2098,0.6869,0.2575,0.6638,0.17300
4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.4000,0.1625,0.2364,0.07678

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)

In [ ]:
X_train

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
338,338,10.050,17.53,64.41,310.8,0.10070,0.07326,0.02511,0.01775,0.1890,...,0.002778,11.160,26.84,71.98,384.0,0.14020,0.1055,0.06499,0.2894,0.07664
427,427,10.800,21.98,68.79,359.9,0.08801,0.05743,0.03614,0.01404,0.2016,...,0.002690,12.760,32.04,83.69,489.5,0.13030,0.1927,0.07485,0.2965,0.07662
406,406,16.140,14.86,104.30,800.0,0.09495,0.08501,0.05500,0.04528,0.1735,...,0.001621,17.710,19.58,115.90,947.9,0.12060,0.2310,0.11290,0.2778,0.07012
96,96,12.180,17.84,77.79,451.1,0.10450,0.07057,0.02490,0.02941,0.1900,...,0.003408,12.830,20.92,82.14,495.2,0.11400,0.0498,0.05882,0.2227,0.07376
490,490,12.250,22.44,78.18,466.5,0.08192,0.05200,0.01714,0.01261,0.1544,...,0.002399,14.170,31.99,92.74,622.9,0.12560,0.1230,0.06335,0.3100,0.08203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,277,18.810,19.98,120.90,1102.0,0.08923,0.05884,0.08020,0.05843,0.1550,...,0.001676,19.960,24.30,129.00,1236.0,0.12430,0.2210,0.12940,0.2567,0.05737
9,9,12.460,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,0.010080,15.090,40.68,97.65,711.4,0.18530,1.1050,0.22100,0.4366,0.20750
359,359,9.436,18.32,59.82,278.6,0.10090,0.05956,0.02710,0.01406,0.1506,...,0.002713,12.020,25.02,75.79,439.6,0.13330,0.1144,0.05052,0.2454,0.08136
192,192,9.720,18.22,60.73,288.1,0.06950,0.02344,0.00000,0.00000,0.1653,...,0.001688,9.968,20.83,62.25,303.8,0.07117,0.0000,0.00000,0.1909,0.06559
559,559,11.510,23.93,74.52,403.5,0.09261,0.10210,0.11120,0.04105,0.1388,...,0.004738,12.480,37.16,82.28,474.2,0.12980,0.3630,0.09653,0.2112,0.08732

In [ ]:
X_test

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
512,512,13.40,20.52,88.64,556.7,0.11060,0.14690,0.14450,0.08172,0.2116,...,0.004005,16.41,29.66,113.30,844.4,0.15740,0.51060,0.20510,0.3585,0.11090
457,457,13.21,25.25,84.10,537.9,0.08791,0.05205,0.02772,0.02068,0.1619,...,0.001828,14.35,34.23,91.29,632.9,0.12890,0.13900,0.06005,0.2444,0.06788
439,439,14.02,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,...,0.002104,14.91,19.31,96.53,688.9,0.10340,0.06260,0.08216,0.2136,0.06710
298,298,14.26,18.17,91.22,633.1,0.06576,0.05220,0.02475,0.01374,0.1635,...,0.001957,16.22,25.26,105.80,819.7,0.09445,0.15650,0.07530,0.2636,0.07676
37,37,13.03,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.02923,0.1467,...,0.001777,13.30,22.81,84.46,545.9,0.09701,0.04833,0.05013,0.1987,0.06169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,213,17.42,25.56,114.50,948.0,0.10060,0.11460,0.16820,0.06597,0.1308,...,0.012560,18.07,28.07,120.40,1021.0,0.12430,0.28030,0.10990,0.1603,0.06818
519,519,12.75,16.70,82.51,493.8,0.11250,0.11170,0.03880,0.02995,0.2120,...,0.003629,14.45,21.74,93.63,624.1,0.14750,0.14230,0.08045,0.3071,0.08557
432,432,20.18,19.54,133.80,1250.0,0.11330,0.14890,0.21330,0.12590,0.1724,...,0.004005,22.03,25.07,146.00,1479.0,0.16650,0.53080,0.21730,0.3032,0.08075
516,516,18.31,20.58,120.80,1052.0,0.10680,0.12480,0.15690,0.09451,0.1860,...,0.002725,21.86,26.20,142.20,1493.0,0.14920,0.37590,0.15100,0.3074,0.07863
500,500,15.04,16.74,98.73,689.4,0.09883,0.13640,0.07721,0.06142,0.1668,...,0.003237,16.76,20.43,109.70,856.9,0.11350,0.18560,0.10180,0.2177,0.08549

In [ ]:
y_train

338    0.14020
427    0.16960
406    0.17220
96     0.09358
490    0.18040
        ...
277    0.11600
9      1.05800
359    0.10490
192    0.02729
559    0.25170
Name: worst compactness, Length: 455, dtype: float64

In [ ]:
y_test

512    0.38560
457    0.10630
439    0.10170
298    0.21670
37     0.04619
        ...
213    0.17930
519    0.19790
432    0.29420
516    0.25360
500    0.21760
Name: worst compactness, Length: 114, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

1. LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(ly_preds, y_test))


def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test))

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test))

평균제곱근오차 0.0005204237064859748
평균제곱근오차 0.0005204237064859748
평균제곱근오차 0.0005204237064859746

2. Decision Tree Regressor

In [ ]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 0.005567390942105263

3. Random Forest Regressor

In [ ]:
model = RandomForestRegressor()
model.fit(X_train, y_train)
ry_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test))

평균제곱근오차 0.0022819438806333304